@include ('layouts.terms-header')


<button class="login-btn" onclick="window.location.href='{{ route('login') }}'">Volver al Login</button>
<h3 style= "margin-left:4rem; "> Terminos y condiciones:</h3>
<p style="white-space: pre-line; text-align: center; margin-left:4rem; margin-right:4rem">

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean posuere sem massa, maximus scelerisque risus imperdiet in. Cras in nulla hendrerit, sodales mi et, euismod turpis. Integer sodales dolor odio, in lacinia elit ultrices quis. Donec porttitor lacinia enim, eu tempus dolor ultrices at. Suspendisse et magna accumsan, vulputate sapien nec, iaculis ligula. In elementum commodo enim non tempor. Suspendisse elit elit, facilisis at elit eget, bibendum aliquet ipsum. Praesent tincidunt, elit vel posuere sagittis, neque velit varius leo, nec pharetra sapien mauris sit amet ante. Curabitur orci magna, pellentesque eu sapien nec, pretium finibus turpis. Duis dui tortor, dapibus sit amet justo et, tempor feugiat massa. Quisque dolor felis, pellentesque nec porta in, sollicitudin ut tellus.

    Phasellus dolor mauris, eleifend vel maximus vel, volutpat a sem. Nulla rhoncus, dui sed venenatis euismod, dolor diam auctor est, quis dapibus ante enim eget ante. Nunc lobortis nunc vitae ante convallis, sit amet vehicula dui euismod. Cras blandit ornare tortor, nec gravida orci ultricies eget. Donec quis egestas arcu. Vivamus elementum mollis nunc, vitae congue mi condimentum nec. Curabitur vitae euismod nunc, vel scelerisque velit. Nunc eu dapibus odio, fermentum dignissim nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent malesuada leo metus, nec fringilla tortor dignissim ut.

    Mauris viverra nisl nec ipsum pretium efficitur. Maecenas vulputate vestibulum finibus. Nam vitae convallis odio, ac pretium arcu. Nullam et massa enim. Nam luctus nibh libero, vitae aliquam lorem pellentesque porta. Nam consectetur diam ac velit consectetur, vitae interdum justo maximus. Duis maximus vel risus sit amet dictum. Nullam in cursus velit. Integer eu purus justo. Proin at odio turpis. Aenean eget erat non augue semper consectetur quis at magna. Nunc varius, ipsum fermentum ultricies euismod, augue erat placerat turpis, interdum consectetur nibh odio eu dui. Cras quis lectus pharetra, imperdiet risus eget, convallis ex. Cras pretium nec eros et finibus. Maecenas cursus posuere vulputate.

    Cras malesuada sodales eros in hendrerit. Sed varius scelerisque est in sodales. Quisque tempus pharetra orci convallis lacinia. Aenean sed ipsum et turpis aliquet condimentum. Ut rutrum mi ex, id condimentum lacus varius blandit. Aenean fermentum justo ac tellus malesuada viverra. Fusce porta velit tempus mollis congue.

    Mauris et justo a diam porta lacinia. Integer aliquet porta consequat. In aliquet, purus vitae tempus volutpat, leo nunc egestas tortor, quis efficitur ipsum tortor ac mi. Morbi sagittis bibendum diam, vel tempor tortor dictum id. Pellentesque nec tempus mi. Donec non euismod mauris, sit amet consequat nulla. In egestas quis lorem sed scelerisque. Phasellus suscipit sollicitudin varius. Nulla facilisi. Maecenas sit amet nunc a sem fringilla auctor quis ac sapien.

    Morbi tempus velit at tellus ultrices, sit amet molestie quam sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent at risus accumsan, placerat augue nec, dignissim ante. Duis congue blandit metus, non egestas ligula dignissim vel. Etiam sed neque in lorem rutrum gravida sed vel ante. Proin sagittis ac sem volutpat sollicitudin. Pellentesque egestas dictum massa, at sagittis eros varius sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus.

    Donec sagittis egestas ex vel dictum. Nullam condimentum, nunc eget dictum aliquet, velit arcu porttitor augue, nec posuere nisl ante quis eros. Vivamus molestie nisi ac porttitor vehicula. Morbi neque massa, tempor sed ante sollicitudin, dapibus elementum nisi. Fusce euismod erat vitae tellus auctor, eu vulputate lectus scelerisque. Suspendisse potenti. Praesent feugiat, augue nec interdum fringilla, lacus sem tempor sem, ut sodales lectus enim ac erat. Nunc vehicula elementum quam. Nunc fringilla scelerisque tempus. Aliquam vel tortor nec diam viverra rhoncus. Proin est quam, sagittis tristique faucibus id, scelerisque in justo. Pellentesque sed orci in lectus pharetra sagittis a sed purus. Nunc pretium justo lectus, et vehicula nisl semper maximus. Interdum et malesuada fames ac ante ipsum primis in faucibus.

    Integer dapibus egestas nisi, et blandit ex pellentesque id. Donec dui diam, feugiat vel euismod vel, elementum vitae elit. Ut porttitor varius dictum. Curabitur rutrum lacinia nunc ac pretium. Maecenas ut felis diam. Nunc dictum dolor eu odio porta commodo. Ut ultrices, sapien id tincidunt porta, elit risus mattis sapien, eu ultricies magna ipsum ut ligula. Nullam mauris augue, vulputate et tortor sit amet, vestibulum ultricies nibh. Integer id dolor pulvinar, ullamcorper odio in, viverra eros. Mauris dui nibh, convallis nec odio non, luctus mollis tellus. Vestibulum ligula lorem, vestibulum ac mollis nec, iaculis in nunc. Quisque tellus erat, sodales non nisi at, porttitor laoreet lectus. Vestibulum sed eros congue, scelerisque enim id, malesuada ipsum.

    Nulla eget tristique lorem. Morbi quis efficitur ex. Aenean tempus lorem nec sapien consectetur, vel viverra diam rutrum. Phasellus fringilla nec purus eget maximus. Maecenas consectetur orci vitae nisi pellentesque interdum. Cras condimentum velit quis justo auctor tempus et eget massa. Maecenas faucibus pellentesque aliquet. Duis vehicula non turpis vel tempor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur imperdiet est velit, auctor rhoncus eros vehicula id. Cras malesuada urna quis cursus mollis.

    Mauris dapibus mollis efficitur. Suspendisse dignissim augue id condimentum vestibulum. Nulla lobortis erat a ante auctor efficitur. Sed tempus a nisl quis pellentesque. Cras dui sem, tristique vel sodales eget, ornare eu justo. Etiam nunc lacus, tempus ut maximus sed, tincidunt molestie nisl. Morbi elementum suscipit mi vitae suscipit. Aenean lacus tortor, consectetur quis ipsum nec, blandit vulputate nisl. Vivamus vulputate elit nec ligula eleifend, nec sollicitudin tellus pulvinar. Integer sed dui consequat, tristique augue eget, feugiat augue. Aenean mattis massa tincidunt libero tincidunt dignissim. Quisque accumsan eu ipsum eget condimentum. Integer varius bibendum metus, et euismod mi convallis a. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum nec nibh lectus. Vestibulum pellentesque a ipsum eu facilisis.

    Fusce sollicitudin convallis leo eu venenatis. Vivamus ut maximus ante, et sagittis mauris. Nulla lacinia maximus enim, eget dictum tellus molestie vitae. In vel ornare odio, quis rutrum velit. Sed iaculis blandit porttitor. Curabitur ac ultrices risus. Nullam facilisis lorem a sollicitudin efficitur. In interdum ornare tincidunt. Quisque vitae porta nisi, ut dictum arcu. Proin at eleifend erat. Aenean vitae libero tellus. Suspendisse potenti. Integer tempor in felis non accumsan. Ut vel arcu tempor, congue augue vitae, vehicula libero. Maecenas eu sem sed ligula tempor mattis.

    Sed fermentum felis sed metus aliquet bibendum. Proin et sem ut mauris laoreet dapibus. Suspendisse consectetur scelerisque dui vel commodo. Duis id auctor felis, ac varius eros. Pellentesque mollis nibh ut augue condimentum molestie. Nulla sed ultricies nisi. Mauris tempus porttitor neque, eget luctus justo suscipit aliquam. Quisque vestibulum eros vitae venenatis pulvinar. Nulla at nibh et arcu vulputate vulputate ultrices ut nunc. Donec id erat velit. Aenean ipsum dolor, ultrices ac magna et, mattis gravida erat. Nulla facilisi. Quisque pharetra scelerisque orci, quis pellentesque est elementum vitae. Duis tincidunt maximus massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra libero vitae ultricies molestie.
</p>
